jaypeak/transactions/models.py
from sqlalchemy import func

from flask_login import UserMixin, AnonymousUserMixin
from flask_security import RoleMixin

from ..extensions import db, login_manager

roles_users = db.Table(
    'roles_users',
    db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
    db.Column('role_id', db.Integer(), db.ForeignKey('role.id'))
)


class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False)
    description = db.Column(db.String(255))

    def save(self):
        db.session.add(self)
        db.session.commit()


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    yodlee_user_id = db.Column(db.Integer)
    email = db.Column(db.String(255), unique=True, nullable=False)
    _username = db.Column(db.String(255), unique=True)
    recurring_transactions = db.relationship(
        'RecurringTransaction',
        backref='user',
        lazy='dynamic',
        cascade='all,delete-orphan',
    )
    transactions = db.relationship(
        'Transaction',
        backref='user',
        lazy='dynamic',
        cascade='all,delete-orphan',
    )
    roles = db.relationship(
        'Role',
        secondary=roles_users,
        backref=db.backref('users', lazy='dynamic')
    )

    @classmethod
    def get_by_email(cls, email):
        return cls.query.filter_by(email=email).first()

    @property
    def username(self):
        if self._username:
            return self._username

        return 'dollarbackgirl{}'.format(self.id)

    def has_role(self, role):
        return role in self.roles

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return '<User %r>' % self.id


class AnonymousUser(AnonymousUserMixin):

    def has_role(self, role):
        return False


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class Transaction(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime, nullable=False)
    description = db.Column(db.Text, nullable=False)
    account_id = db.Column(db.Integer, nullable=False)
    amount = db.Column(db.Numeric(10, 2), nullable=False)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)
    yodlee_transaction_id = db.Column(db.Integer, nullable=False)
    recurring_transaction_id = db.Column(db.ForeignKey('recurring_transaction.id'))  # nopep8

    @classmethod
    def get_or_create_from_yodlee_transactions(cls, yodlee_transaction, user_id):  # nopep8
        transaction = cls.query.filter_by(
            user_id=user_id,
            yodlee_transaction_id=yodlee_transaction.yodlee_transaction_id
        ).first()
        if transaction:
            return transaction

        yodlee_transaction.user_id = user_id
        yodlee_transaction.save()
        return yodlee_transaction

    def save(self):
        db.session.add(self)
        db.session.commit()


class RecurringTransaction(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)
    transactions = db.relationship(
        'Transaction',
        backref='recurring_transaction',
        lazy='dynamic',
        cascade='all,delete-orphan',
        passive_deletes=True,
    )

    @classmethod
    def add_or_create_by_transaction(cls, transaction):
        recurring_transaction = RecurringTransaction.query.join(
            Transaction
        ).filter(
            RecurringTransaction.user_id == transaction.user_id,
            func.levenshtein(Transaction.description, transaction.description) < 10,  # nopep8
            Transaction.amount == transaction.amount,
        ).first()
        if not recurring_transaction:
            recurring_transaction = RecurringTransaction(
                user_id=transaction.user_id
            )

        recurring_transaction.transactions.append(transaction)
        recurring_transaction.save()
        return recurring_transaction

    @classmethod
    def query_by_user_id(self, user_id):
        return RecurringTransaction.query.join(
            Transaction
        ).filter(
            Transaction.user_id == user_id
        ).group_by(
            RecurringTransaction
        ).having(
            func.count(Transaction.id) > 1
        )

    @property
    def description(self):
        return self.transactions[-1].description

    @property
    def amount(self):
        return self.transactions[-1].amount

    @property
    def date(self):
        return self.transactions[-1].date

    def save(self):
        db.session.add(self)
        db.session.commit()

jaypeak/transactions/forms.py
from flask_wtf import Form
from wtforms import PasswordField, BooleanField, ValidationError
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms.fields.html5 import EmailField

from .models import User


class LoginForm(Form):
    email = EmailField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')


class RegisterForm(Form):
    email = EmailField('Email', validators=[Email(), DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    password_confirm = PasswordField(
        'Confirm Password',
        validators=[DataRequired(), EqualTo('password')]
    )

    def validate_email(self, field):
        user = User.get_by_email(field.data)
        if user:
            raise ValidationError('Email address already in use')

jaypeak/__init__.py
from .app import create_app
from jaypeak.transactions import utils

jaypeak/app.py
import sys
import logging
import os

from flask import Flask, session
from flask_security import SQLAlchemyUserDatastore

from .extensions import bootstrap, db, security, admin, login_manager, yc, \
    toolbar, migrate
from .auth import jwt
from . import transactions
from .api import configure_api_manager
from .transactions import utils
from .transactions.admin import configure_transactions_admin
from .transactions.models import User, Role, AnonymousUser
from .yodlee import ProductionConfig, SandboxConfig


def create_app():
    app = Flask(__name__)
    app.config.from_object(os.environ['CONFIG'])
    app.logger.addHandler(logging.StreamHandler(sys.stdout))
    app.logger.setLevel(logging.ERROR)
    app.register_blueprint(transactions.bp)

    app.before_request(set_cobrand_session_token)

    user_datastore = SQLAlchemyUserDatastore(db, User, Role)
    security.init_app(app, user_datastore)
    jwt.init_app(app)
    bootstrap.init_app(app)
    db.init_app(app)
    admin._views = []
    admin.init_app(app)
    login_manager.init_app(app)
    login_manager.login_view = 'transactions.index'
    login_manager.anonymous_user = AnonymousUser
    migrate.init_app(app, db)

    toolbar.init_app(app)

    configure_transactions_admin(app, db)
    configure_api_manager(app, db)

    if os.environ['CONFIG'] == 'config.ProductionConfig':
        yc.config.from_object(ProductionConfig)
    else:
        yc.config.from_object(SandboxConfig)

        def register_user(*args):
            raise Exception('Disabled in SandboxConfig')

        yc.register_user = register_user

    return app


def set_cobrand_session_token():
    cobrand_session_token = utils.get_yodlee_cobrand_session_token_or_400()
    session['cobrand_session_token'] = cobrand_session_token

jaypeak/auth.py
from flask import jsonify, request, session
from flask_jwt import JWT, jwt_required
from .transactions.models import User
from .transactions import utils

jwt = JWT()


@jwt.authentication_handler
def authentication_handler(email, password):
    user = User.query.filter_by(email=email).first()
    if not user:
        return None

    user, token, error = utils.login_yodlee_user(
        session['cobrand_session_token'],
        user.username,
        password
    )

    if not user:
        return None
    return user


@jwt.identity_handler
def identity_handler(payload):
    user = User.query.get(id=payload['identity'])
    return user


@jwt.auth_response_handler
def auth_response_handler(access_token, identity):
    return jsonify({
        'access_token': access_token.decode('utf-8'),
        'user_id': identity.id
    })


@jwt_required()
def authentication_preprocessor(**kw):
    pass

jaypeak/transactions/__init__.py
from .views import bp

jaypeak/transactions/views.py
from flask import Blueprint, render_template, url_for, redirect, flash, \
    session, abort, request, jsonify
from flask.views import MethodView
from flask_login import login_required, current_user, login_user, logout_user

from ..extensions import yc, db
from .models import RecurringTransaction, User
from .forms import LoginForm, RegisterForm
from . import utils

bp = Blueprint('transactions', __name__)


@bp.route('/')
def index():
    return render_template('transactions/index.html')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    if login_form.validate_on_submit():
        user = User.query.filter_by(email=login_form.email.data).first()

        if user:
            user, token, error = utils.login_yodlee_user(
                session['cobrand_session_token'],
                user.username,
                login_form.password.data
            )
        else:
            error = 'Email not found'

        if not error:
            login_user(user)
            session['user_session_token'] = token

            # Prevents circular imports
            from . import tasks
            tasks.sync_transactions.delay(
                session['cobrand_session_token'],
                session['user_session_token'],
                user.id,
            )
            return redirect(url_for('.recurring_transactions'))

        flash(error, 'danger')

    return render_template(
        'transactions/login.html',
        login_form=login_form
    )


@bp.route('/register', methods=['GET', 'POST'])
def register():
    register_form = RegisterForm()
    if register_form.validate_on_submit():
        user = User(email=register_form.email.data)
        db.session.add(user)
        db.session.flush()

        yodlee_user, token, error = utils.register_yodlee_user(
            session['cobrand_session_token'],
            user.username,
            register_form.password.data,
            user.email,
        )

        if not error:
            user.yodlee_user_id = yodlee_user.yodlee_user_id
            db.session.commit()
            user.save()
            session['user_session_token'] = token
            login_user(user)
            return redirect(url_for('.welcome'))

        db.session.rollback()
        flash(error, 'danger')

    return render_template(
        'transactions/register.html',
        register_form=register_form,
    )


@bp.route('/sync-transactions/status/<id>')
def sync_transactions_status(id):
    # Prevents circular imports
    from . import tasks
    task = tasks.sync_transactions.AsyncResult(id)
    return jsonify({'state': task.state})


@bp.route('/logout')
@login_required
def logout():
    session.pop('user_session_token', None)
    logout_user()
    flash('You are now logged out')
    return redirect(url_for('.login'))


@bp.route('/recurring-transactions')
@login_required
def recurring_transactions():
    if request.args.get('page') is None:
        page = 1
    else:
        page = int(request.args.get('page'))
    query = RecurringTransaction.query_by_user_id(current_user.id)  # nopep8
    recurring_transactions = query.paginate(page, 5, True)
    return render_template(
        'transactions/recurring_transactions.html',
        recurring_transactions=recurring_transactions
    )


@bp.route('/recurring-transactions/<int:id>')
@login_required
def recurring_transaction(id):
    if request.args.get('page') is None:
        page = 1
    else:
        page = int(request.args.get('page'))
    recurring_transaction = RecurringTransaction.query.get_or_404(id)
    if current_user.id != recurring_transaction.user_id:
        abort(404)
    return render_template(
        'transactions/recurring_transaction.html',
        recurring_transaction=recurring_transaction,
        page=page,
    )


@bp.route('/settings')
@login_required
def settings():
    return render_template(
        'transactions/settings.html',
    )


@bp.route('/delete-user')
@login_required
def delete_user():
    utils.unregister_yodlee_user_or_400(
        session['cobrand_session_token'],
        session['user_session_token'],
    )
    current_user.delete()
    logout_user()
    flash('Your account was deleted')
    return redirect(url_for('.index'))


@bp.route('/welcome')
def welcome():
    return render_template('transactions/welcome.html')


@bp.route('/welcome/add-accounts')
@login_required
def add_accounts():
    fastlink_token = utils.get_yodlee_fastlink_token_or_400(
        session['cobrand_session_token'],
        session['user_session_token'],
    )
    fastlink_url = yc.config['FASTLINK_URL']
    return render_template(
        'transactions/add_accounts.html',
        user_session_token=session['user_session_token'],
        fastlink_token=fastlink_token,
        fastlink_url=fastlink_url
    )


@bp.route('/welcome/sync-transactions')
def welcome_sync_transactions():
    # Prevents circular imports
    from . import tasks
    task = tasks.sync_transactions.delay(
        session['cobrand_session_token'],
        session['user_session_token'],
        current_user.id
    )
    url = url_for('.sync_transactions_status', id=task.id)
    return render_template(
        'transactions/sync_transactions.html',
        sync_transactions_status_url=url,
    )


@bp.route('/cobrand_session_token')
def cobrand_session_token():
    cobrand_session_token = utils.get_yodlee_cobrand_session_token_or_400()
    return jsonify({
        'cobrand_session_token': cobrand_session_token
    })


class SyncTransactions(MethodView):

    def get(self, user_id, task_id):
        # Prevents circular imports
        from . import tasks
        task = tasks.sync_transactions.AsyncResult(id)
        return jsonify({
            'state': task.state,
            'id': task.id,
        })

    def post(self, user_id):
        # Prevents circular imports
        from . import tasks
        task = tasks.sync_transactions.delay(
            session['cobrand_session_token'],
            session['user_session_token'],
            user_id
        )
        return jsonify({
            'state': task.state,
            'id': task.id,
        })

sync_transaction_view = SyncTransactions.as_view('sync_transactions')
bp.add_url_rule(
    '/user/<int:user_id>/sync_transactions',
    view_func=sync_transaction_view,
    methods=['POST', ]
)
bp.add_url_rule(
    '/user/<int:user_id>/sync_transactions/<task_id>',
    view_func=sync_transaction_view,
    methods=['GET', ]
)

jaypeak/yodlee/__init__.py
import os

from .client import Client
from .schemas import ErrorResponseMixin, FastlinkTokenResponseMixin, \
    LoginCobrandResponseMixin, LoginUserResponseMixin, \
    RegisterUserResponseMixin


class SandboxConfig(object):
    COBRAND_NAME = 'restserver'
    BASE_URL = 'https://developer.api.yodlee.com/ysl/{}/v1'.format(
        COBRAND_NAME)
    COBRAND_USERNAME = 'sbCobmassover'
    COBRAND_PASSWORD = os.getenv('YODLEE_COBRAND_PASSWORD')
    FASTLINK_URL = 'https://node.developer.yodlee.com/authenticate/restserver/'


class ProductionConfig(object):
    COBRAND_NAME = 'quickstart6'
    BASE_URL = 'https://quickstart.api.yodlee.com/ysl/{}/v1'.format(
        COBRAND_NAME)
    COBRAND_USERNAME = 'quickstart6'
    COBRAND_PASSWORD = os.getenv('YODLEE_COBRAND_PASSWORD')
    FASTLINK_URL = 'https://quickstartnode.yodleeinteractive.com/authenticate/{}/?channelAppName=quickstart'.format(
        COBRAND_NAME)

jaypeak/templates/transactions/add_accounts.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row" style="padding-top: 12px; padding-bottom: 12px;">
        <div class="col-md-12">
                <a href="{{ url_for('transactions.welcome') }}">
                    <button class="btn btn-default" style="font-size: 24px;">
                        <i class="fa fa-chevron-left" aria-hidden="true"></i>Back
                    </button>
                </a>
                <a href="{{ url_for('transactions.welcome_sync_transactions') }}" class="pull-right">
                    <button class="btn btn-default" style="font-size: 24px;">
                        Next<i class="fa fa-chevron-right" aria-hidden="true"></i>
                    </button>
                </a>
        </div>
    </div>
</div>
<div class="container-fluid" id="fastlink" style="display: none;">
    <div class="row">
        <iframe name="my-iframe" src="{{ fastlink_url }}"></iframe>
    </div>

    <form action="{{ fastlink_url }}"
          id="fastlinkForm" target="my-iframe" method="post">

        <input type="hidden" name="app" value="10003600">
        <input type="hidden" name="rsession" value="{{ user_session_token }}">
        <input type="hidden" name="token" value="{{ fastlink_token }}">
        <input type="hidden" name="redirectReq" value=true>
    </form>


    <script type="text/javascript">
        document.getElementById('fastlinkForm').submit();
        document.getElementById('fastlink').style.display = 'block';
        document.getElementById('fastlink').style.border = '1px solid #eee';
    </script>
</div>
{% endblock %}

jaypeak/templates/transactions/fastlink.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
    <form action="{{ fastlink_url }}"
          id="fastlinkForm" target="my-iframe" method="post">

        <input type="hidden" name="app" value="10003600">
        <input type="hidden" name="rsession" value="{{ user_session_token }}">
        <input type="hidden" name="token" value="{{ fastlink_token }}">
        <input type="hidden" name="redirectReq" value=true>
    </form>

    <!-- Modal -->
    <div class="modal show" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         data-backdrop="static" data-keyboard="false">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <div class="row">
                <div class="col-xs-8">
                    <h4 class="modal-title" id="myModalLabel">Add your accounts</h4>
                </div>
                <div class="col-xs-4">
                    <button type="button" class="btn btn-primary pull-right">Done</button>
                </div>
            </div>
          </div>
            <iframe id="fastlink" name="my-iframe" src="{{ fastlink_url }}" style="display: none;">
            </iframe>
        </div>
      </div>
    </div>


    <script type="text/javascript">
        document.getElementById('fastlinkForm').submit();
        document.getElementById('fastlink').style.display = 'block';
    </script>
</div>
{% endblock %}

jaypeak/templates/transactions/index.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
{% include 'flash.html' %}
<div class="container-fluid">
    <div class="row" style="padding-top: 60px;">
        <div class="col-md-offset-2 col-md-8 text-center">
            <h1 class="index">Dollar Back Girl</h1>
            <h3 class="index">Manage your recurring payments</h3>
        </div>
    </div>
    <div class="row" style="padding-top: 60px;">
        <div class="col-md-offset-4 col-md-4">
            <a href="{{ url_for('transactions.login') }}" class="btn btn-primary btn-lg btn-block">LOGIN</a>
            <a href="{{ url_for('transactions.register') }}" class="btn btn-default btn-lg btn-block">REGISTER</a>
        </div>
    </div>
</div>
{% endblock %}

jaypeak/templates/transactions/login.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container-fluid">
    <div class="row" style="padding-top: 60px;">
        <div class="col-md-offset-3 col-md-6">
            {% include 'transactions/login_form.html' %}
        </div>
    </div>
</div>
{% endblock %}

jaypeak/templates/transactions/login_form.html
{% import "bootstrap/wtf.html" as wtf %}

<form method="POST" action="{{ url_for('transactions.login') }}">

    <h1 class="text-center">Login</h1>

    {{ login_form.hidden_tag() }}

    {% include 'flash.html' %}

    {% if login_form.email.errors %}
        <div class="form-group has-error">
            {{ login_form.email(class="form-control", placeholder="Email") }}
            <p class="help-block">{{ login_form.email.errors[0] }}</p>
        </div>
    {% else %}
        {{ login_form.email(class="form-group form-control", placeholder="Email") }}
    {% endif %}

    {% if login_form.password.errors %}
        <div class="form-group has-error">
            {{ login_form.password(class="form-control", placeholder="Password") }}
            <p class="help-block">{{ login_form.password.errors[0] }}</p>
        </div>
    {% else %}
        {{ login_form.password(class="form-group form-control", placeholder="Password") }}
    {% endif %}

    <button type="submit" class="btn btn-default btn-lg btn-block">Login</button>
    <a
    type="button"
    href="{{ url_for('transactions.register' )}}"
    class="btn btn-primary btn-lg btn-block">
        Register
    </a>
</form>

jaypeak/templates/transactions/recurring_transactions.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="padding-top: 60px;">
    <div class="list-group">
     <div class="list-group-item">
        <div class="row text-center text-bold">
            <div class="col-xs-3">
                <h4><strong>Date</strong></h4>
            </div>
            <div class="col-xs-6">
                <h4><strong>Description</strong></h4>
            </div>
            <div class="col-xs-3">
                <h4><strong>Amount</strong></h4>
            </div>
        </div>
    </div>
        {% for recurring_transaction in recurring_transactions.items %}
            <a href="{{ url_for('transactions.recurring_transaction', id=recurring_transaction.id) }}"
               class="list-group-item">

                <div class="row text-center">
                    <div class="col-xs-3">
                        <span>{{ recurring_transaction.date}}<span>
                    </div>
                    <div class="col-xs-6 text-left">
                        <span>{{ recurring_transaction.description }}</span>
                    </div>
                    <div class="col-xs-3">
                        <span>${{ recurring_transaction.amount }}</span>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
    {% from "bootstrap/pagination.html" import render_pagination %}
    {{ render_pagination(recurring_transactions) }}
</div>
{% endblock %}

jaypeak/templates/transactions/register.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container-fluid">
    <div class="row" style="padding-top: 60px;">
        <div class="col-md-offset-3 col-md-6">
            {% include 'transactions/register_form.html' %}
        </div>
    </div>
</div>
{% endblock %}

jaypeak/templates/transactions/register_form.html
{% import "bootstrap/wtf.html" as wtf %}

<form method="POST" action="{{ url_for('transactions.register') }}">

    <h1 class="text-center">Register</h1>

    {{ register_form.hidden_tag() }}

    {% include 'flash.html' %}

    {% if register_form.email.errors %}
        <div class="form-group has-error">
            {{ register_form.email(class="form-control", placeholder="Email") }}
            <p class="help-block">{{ register_form.email.errors[0] }}</p>
        </div>
    {% else %}
        {{ register_form.email(class="form-group form-control", placeholder="Email") }}
    {% endif %}

    {% if register_form.password.errors %}
        <div class="form-group has-error">
            {{ register_form.password(class="form-control", placeholder="Password") }}
            <p class="help-block">{{ register_form.password.errors[0] }}</p>
        </div>
    {% else %}
        {{ register_form.password(class="form-group form-control", placeholder="Password") }}
    {% endif %}

    <p class="help-block">
        Use 8 or more characters
    </p>
    <p class="help-block">
        Use an upper case letter
    </p>
    <p class="help-block">
        Use one number
    </p>

    <p class="help-block">
        Use any of these special characters !@#$%^&*() ]
    </p>


    {% if register_form.password_confirm.errors %}
        <div class="form-group has-error">
            {{ register_form.password_confirm(class="form-control", placeholder="Password") }}
            <p class="help-block">{{ register_form.password_confirm.errors[0] }}</p>
        </div>
    {% else %}
        {{ register_form.password_confirm(class="form-group form-control", placeholder="Confirm Password") }}
    {% endif %}

    <button type="submit" class="btn btn-default btn-lg btn-block">Submit</button>

</form>

jaypeak/templates/transactions/settings.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="padding-top: 20px;">

    <div class="row">
        <div class="col-xs-3">
            <ul class="nav nav-pills nav-stacked">
                  <li role="presentation" class="active">
                      <a href="{{ url_for('transactions.settings') }}">Profile</a>
                  </li>
                  <li role="presentation">
                      <a href="{{ url_for('transactions.logout') }}">Logout</a>
                  </li>
            </ul>
        </div>
        <div class="col-xs-9">
            <h3>Delete this account
                <span class="pull-right">
                    <button class="btn btn-danger btn-lg"
                            data-toggle="modal"
                            data-target="#delete-account">
                        Delete this account
                    </button>
                </span>

            </h3>
            <p class="text-muted">This cannot be undone</p>

        </div>
    </div>

    <div id="delete-account" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="deleteAccount">
      <div class="modal-dialog modal-md">
        <div class="modal-content">
             <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Are you sure you want to delete this account?</h4>
             </div>
             <div class="modal-body">
                This cannot be undone
             </div>
             <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    Close
                </button>
                <a href="{{ url_for('transactions.delete_user') }}" type="button" class="btn btn-danger">
                    Delete it
                </a>
             </div>
        </div>
      </div>
    </div>

</div>
{% endblock %}

jaypeak/templates/transactions/sync_transactions.html
{% extends "base.html" %}

{% block content %}
<div class="container">

    <h2>It's time to save</h2>
    <h2><small>Find and cancel your recurring payments</small></h2>
    <div class="list-group">
        <div class="list-group-item disabled">
            <div class="row">
                <div class="col-xs-12" style="font-size: 20px">
                    <i class="fa fa-check-square-o" aria-hidden="true"></i>
                    Add your accounts
                </div>
            </div>
        </div>
        <div id="sync-transactions-incomplete" class="list-group-item">
            <div class="row">
                <div class="col-xs-10" style="font-size: 20px">
                    <i class="fa fa-square-o" aria-hidden="true"></i>
                    Finding reccuring transactions
                </div>
                <div class="col-xs-2" style="font-size: 20px">
                    <i class="fa fa-spinner fa-spin pull-right" aria-hidden="true"></i>
                </div>
            </div>
        </div>

        <div id="sync-transactions-complete" class="list-group-item hidden disabled">
            <div class="row">
                <div class="col-xs-12" style="font-size: 20px">
                    <i class="fa fa-check-square-o" aria-hidden="true"></i>
                    Finding reccuring transactions
                </div>
            </div>
        </div>
    </div>
    <a id="next-button" class="btn btn-default btn-lg hidden"
       href="{{ url_for('transactions.recurring_transactions') }}" >
        Next
    </a>
    <script type="text/javascript">
        var SYNC_TRANSACTIONS_STATUS_URL = '{{ sync_transactions_status_url }}';
    </script>

</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{url_for('static', filename='js/sync-transactions.js')}}"></script>
{% endblock %}

jaypeak/templates/transactions/welcome.html
{% extends "base.html" %}

{% block content %}
<div class="container">

    <h2>It's time to save</h2>
    <h2><small>Find and cancel your recurring payments</small></h2>
    <div class="list-group">
        <div class="list-group-item">
            <div class="row">
                <div class="col-xs-8" style="font-size: 20px">
                    <i class="fa fa-square-o" aria-hidden="true"></i>
                    Add accounts
                </div>
                <div class="col-xs-4">
                    <a href="{{ url_for('transactions.add_accounts') }}" class="btn btn-default pull-right">
                        Add accounts
                    </a>
                </div>
            </div>
        </div>
        <div class="list-group-item disabled">
            <div class="row">
                <div class="col-xs-12 text-muted" style="font-size: 20px">
                    <i class="fa fa-square-o" aria-hidden="true"></i>
                    Find recurring transactions
                </div>
            </div>
        </div>
    </div>



</div>
{% endblock %}